# Example
# items:
#   - name: "Item Name"
#     min_volume: 100 (Optional)
#     min_profit: 5.0 (Optional)
items:
  - name: "Sealed Genesis Terminal"
  - name: "Fracture Case"
  - name: "Gallery Case"
  - name: "Falchion Case"
  - name: "Sticker | Scorch Loop (Reverse)"
