# Example
# items:
#   - name: "Item Name"
#     min_volume: 100 (Optional)
#     min_profit: 5.0 (Optional)
items:
  - name: "Fracture Case"
  - name: "Budapest 2025 Mirage Souvenir Package"
  - name: "Sealed Genesis Terminal"
  - name: "Gallery Case"
  - name: "AK-47 | Redline (Field-Tested)"
