[project]
name = "automarket"
version = "0.1.0"
description = "A Python service that periodically checks Steam Market prices and notifies on good deals"
requires-python = ">=3.13"
dependencies = [
    "httpx>=0.28.1",
]
